/**
 * Particle type definitions, colors, densities, and property tables.
 * All particle types use numeric enum values (0-24) for Uint8Array storage.
 */

// Numeric enum — values stored directly in Uint8Array
export const enum ParticleType {
  Empty     = 0,
  Sand      = 1,
  Water     = 2,
  Stone     = 3,
  Fire      = 4,
  Wood      = 5,
  Oil       = 6,
  Smoke     = 7,
  Steam     = 8,
  Gunpowder = 9,
  Lava      = 10,
  Acid      = 11,
  Plant     = 12,
  Ice       = 13,
  Salt      = 14,
  Glass     = 15,
  Metal     = 16,
  Ember     = 17,
  Mud       = 18,
  Mercury   = 19,
  ToxicGas  = 20,
  Hydrogen  = 21,
  Fuse      = 22,
  Clone     = 23,
  Void      = 24,
}

/** Total number of particle types (including Empty) */
export const PARTICLE_COUNT = 25;

export const PARTICLE_NAMES: Record<ParticleType, string> = {
  [ParticleType.Empty]:     "Empty",
  [ParticleType.Sand]:      "Sand",
  [ParticleType.Water]:     "Water",
  [ParticleType.Stone]:     "Stone",
  [ParticleType.Fire]:      "Fire",
  [ParticleType.Wood]:      "Wood",
  [ParticleType.Oil]:       "Oil",
  [ParticleType.Smoke]:     "Smoke",
  [ParticleType.Steam]:     "Steam",
  [ParticleType.Gunpowder]: "Gunpowder",
  [ParticleType.Lava]:      "Lava",
  [ParticleType.Acid]:      "Acid",
  [ParticleType.Plant]:     "Plant",
  [ParticleType.Ice]:       "Ice",
  [ParticleType.Salt]:      "Salt",
  [ParticleType.Glass]:     "Glass",
  [ParticleType.Metal]:     "Metal",
  [ParticleType.Ember]:     "Ember",
  [ParticleType.Mud]:       "Mud",
  [ParticleType.Mercury]:   "Mercury",
  [ParticleType.ToxicGas]:  "Toxic Gas",
  [ParticleType.Hydrogen]:  "Hydrogen",
  [ParticleType.Fuse]:      "Fuse",
  [ParticleType.Clone]:     "Clone",
  [ParticleType.Void]:      "Void",
};

export const DENSITY: Record<ParticleType, number> = {
  [ParticleType.Empty]:     0,
  [ParticleType.Sand]:      90,
  [ParticleType.Water]:     40,
  [ParticleType.Stone]:     255,
  [ParticleType.Fire]:      -10,
  [ParticleType.Wood]:      200,
  [ParticleType.Oil]:       30,
  [ParticleType.Smoke]:     -5,
  [ParticleType.Steam]:     -15,
  [ParticleType.Gunpowder]: 85,
  [ParticleType.Lava]:      100,
  [ParticleType.Acid]:      45,
  [ParticleType.Plant]:     150,
  [ParticleType.Ice]:       80,
  [ParticleType.Salt]:      88,
  [ParticleType.Glass]:     200,
  [ParticleType.Metal]:     250,
  [ParticleType.Ember]:     70,
  [ParticleType.Mud]:       60,
  [ParticleType.Mercury]:   150,
  [ParticleType.ToxicGas]:  -8,
  [ParticleType.Hydrogen]:  -20,
  [ParticleType.Fuse]:      150,
  [ParticleType.Clone]:     255,
  [ParticleType.Void]:      255,
};

export const IS_LIQUID: Record<ParticleType, boolean> = {
  [ParticleType.Empty]:     false,
  [ParticleType.Sand]:      false,
  [ParticleType.Water]:     true,
  [ParticleType.Stone]:     false,
  [ParticleType.Fire]:      false,
  [ParticleType.Wood]:      false,
  [ParticleType.Oil]:       true,
  [ParticleType.Smoke]:     false,
  [ParticleType.Steam]:     false,
  [ParticleType.Gunpowder]: false,
  [ParticleType.Lava]:      true,
  [ParticleType.Acid]:      true,
  [ParticleType.Plant]:     false,
  [ParticleType.Ice]:       false,
  [ParticleType.Salt]:      false,
  [ParticleType.Glass]:     false,
  [ParticleType.Metal]:     false,
  [ParticleType.Ember]:     false,
  [ParticleType.Mud]:       true,
  [ParticleType.Mercury]:   true,
  [ParticleType.ToxicGas]:  false,
  [ParticleType.Hydrogen]:  false,
  [ParticleType.Fuse]:      false,
  [ParticleType.Clone]:     false,
  [ParticleType.Void]:      false,
};

export const IS_GAS: Record<ParticleType, boolean> = {
  [ParticleType.Empty]:     false,
  [ParticleType.Sand]:      false,
  [ParticleType.Water]:     false,
  [ParticleType.Stone]:     false,
  [ParticleType.Fire]:      true,
  [ParticleType.Wood]:      false,
  [ParticleType.Oil]:       false,
  [ParticleType.Smoke]:     true,
  [ParticleType.Steam]:     true,
  [ParticleType.Gunpowder]: false,
  [ParticleType.Lava]:      false,
  [ParticleType.Acid]:      false,
  [ParticleType.Plant]:     false,
  [ParticleType.Ice]:       false,
  [ParticleType.Salt]:      false,
  [ParticleType.Glass]:     false,
  [ParticleType.Metal]:     false,
  [ParticleType.Ember]:     false,
  [ParticleType.Mud]:       false,
  [ParticleType.Mercury]:   false,
  [ParticleType.ToxicGas]:  true,
  [ParticleType.Hydrogen]:  true,
  [ParticleType.Fuse]:      false,
  [ParticleType.Clone]:     false,
  [ParticleType.Void]:      false,
};

export const IS_FLAMMABLE: Record<ParticleType, boolean> = {
  [ParticleType.Empty]:     false,
  [ParticleType.Sand]:      false,
  [ParticleType.Water]:     false,
  [ParticleType.Stone]:     false,
  [ParticleType.Fire]:      false,
  [ParticleType.Wood]:      true,
  [ParticleType.Oil]:       true,
  [ParticleType.Smoke]:     false,
  [ParticleType.Steam]:     false,
  [ParticleType.Gunpowder]: true,
  [ParticleType.Lava]:      false,
  [ParticleType.Acid]:      false,
  [ParticleType.Plant]:     true,
  [ParticleType.Ice]:       false,
  [ParticleType.Salt]:      false,
  [ParticleType.Glass]:     false,
  [ParticleType.Metal]:     false,
  [ParticleType.Ember]:     false,
  [ParticleType.Mud]:       false,
  [ParticleType.Mercury]:   false,
  [ParticleType.ToxicGas]:  true,
  [ParticleType.Hydrogen]:  true,
  [ParticleType.Fuse]:      true,
  [ParticleType.Clone]:     false,
  [ParticleType.Void]:      false,
};

export const IS_STATIC: Record<ParticleType, boolean> = {
  [ParticleType.Empty]:     true,
  [ParticleType.Sand]:      false,
  [ParticleType.Water]:     false,
  [ParticleType.Stone]:     true,
  [ParticleType.Fire]:      false,
  [ParticleType.Wood]:      true,
  [ParticleType.Oil]:       false,
  [ParticleType.Smoke]:     false,
  [ParticleType.Steam]:     false,
  [ParticleType.Gunpowder]: false,
  [ParticleType.Lava]:      false,
  [ParticleType.Acid]:      false,
  [ParticleType.Plant]:     true,
  [ParticleType.Ice]:       true,
  [ParticleType.Salt]:      false,
  [ParticleType.Glass]:     true,
  [ParticleType.Metal]:     true,
  [ParticleType.Ember]:     false,
  [ParticleType.Mud]:       false,
  [ParticleType.Mercury]:   false,
  [ParticleType.ToxicGas]:  false,
  [ParticleType.Hydrogen]:  false,
  [ParticleType.Fuse]:      true,
  [ParticleType.Clone]:     true,
  [ParticleType.Void]:      true,
};

export const MAX_LIFETIME: Record<ParticleType, number> = {
  [ParticleType.Empty]:     0,
  [ParticleType.Sand]:      0,
  [ParticleType.Water]:     0,
  [ParticleType.Stone]:     0,
  [ParticleType.Fire]:      70,
  [ParticleType.Wood]:      0,
  [ParticleType.Oil]:       0,
  [ParticleType.Smoke]:     100,
  [ParticleType.Steam]:     140,
  [ParticleType.Gunpowder]: 0,
  [ParticleType.Lava]:      0,
  [ParticleType.Acid]:      0,
  [ParticleType.Plant]:     0,
  [ParticleType.Ice]:       0,
  [ParticleType.Salt]:      0,
  [ParticleType.Glass]:     0,
  [ParticleType.Metal]:     0,
  [ParticleType.Ember]:     50,
  [ParticleType.Mud]:       0,
  [ParticleType.Mercury]:   0,
  [ParticleType.ToxicGas]:  80,
  [ParticleType.Hydrogen]:  120,
  [ParticleType.Fuse]:      0,
  [ParticleType.Clone]:     0,
  [ParticleType.Void]:      0,
};

export const PARTICLE_COLORS: Record<ParticleType, [number, number, number][]> = {
  [ParticleType.Empty]:     [[10, 10, 15]],
  [ParticleType.Sand]:      [[214, 190, 140], [222, 198, 148], [206, 182, 132], [198, 174, 124]],
  [ParticleType.Water]:     [[30, 80, 180], [40, 90, 195], [25, 70, 170], [35, 85, 190]],
  [ParticleType.Stone]:     [[80, 80, 85], [75, 75, 80], [85, 85, 90], [70, 70, 78]],
  [ParticleType.Fire]:      [[255, 100, 20], [255, 160, 10], [255, 200, 50], [220, 60, 5]],
  [ParticleType.Wood]:      [[100, 65, 30], [110, 75, 40], [90, 55, 25], [95, 60, 28]],
  [ParticleType.Oil]:       [[50, 40, 30], [45, 35, 25], [55, 45, 35], [42, 32, 22]],
  [ParticleType.Smoke]:     [[60, 60, 65], [55, 55, 60], [65, 65, 70], [50, 50, 58]],
  [ParticleType.Steam]:     [[200, 210, 225], [190, 200, 215], [210, 220, 235], [195, 205, 220]],
  [ParticleType.Gunpowder]: [[60, 60, 60], [55, 55, 55], [65, 60, 55], [50, 50, 52]],
  [ParticleType.Lava]:      [[200, 50, 10], [220, 80, 5], [180, 30, 5], [240, 100, 15]],
  [ParticleType.Acid]:      [[120, 240, 40], [100, 220, 30], [140, 255, 50], [110, 230, 35]],
  [ParticleType.Plant]:     [[30, 140, 40], [40, 160, 50], [25, 120, 35], [35, 150, 45]],
  [ParticleType.Ice]:       [[180, 220, 255], [170, 210, 245], [190, 228, 255], [160, 200, 240]],
  [ParticleType.Salt]:      [[230, 230, 232], [240, 240, 242], [220, 220, 225], [235, 235, 238]],
  [ParticleType.Glass]:     [[180, 210, 230], [170, 200, 222], [190, 218, 238], [175, 205, 225]],
  [ParticleType.Metal]:     [[140, 145, 158], [130, 135, 148], [150, 155, 168], [125, 130, 142]],
  [ParticleType.Ember]:     [[200, 60, 10], [180, 40, 5], [220, 80, 15], [190, 50, 8]],
  [ParticleType.Mud]:       [[90, 60, 35], [80, 50, 28], [100, 70, 42], [85, 55, 30]],
  [ParticleType.Mercury]:   [[160, 165, 182], [170, 175, 192], [150, 155, 172], [165, 170, 188]],
  [ParticleType.ToxicGas]:  [[140, 180, 40], [130, 170, 35], [150, 190, 48], [135, 175, 38]],
  [ParticleType.Hydrogen]:  [[200, 212, 232], [210, 222, 242], [190, 202, 222], [205, 218, 238]],
  [ParticleType.Fuse]:      [[120, 50, 30], [130, 58, 35], [110, 42, 25], [125, 52, 32]],
  [ParticleType.Clone]:     [[180, 50, 200], [190, 60, 212], [170, 40, 190], [185, 55, 205]],
  [ParticleType.Void]:      [[30, 10, 42], [25, 8, 35], [35, 12, 48], [20, 5, 30]],
};

export const UI_COLORS: Partial<Record<ParticleType, string>> = {
  [ParticleType.Sand]:      "#d6be8c",
  [ParticleType.Water]:     "#1e50b4",
  [ParticleType.Stone]:     "#505055",
  [ParticleType.Fire]:      "#ff6414",
  [ParticleType.Wood]:      "#6e4528",
  [ParticleType.Oil]:       "#322820",
  [ParticleType.Smoke]:     "#3c3c41",
  [ParticleType.Steam]:     "#c8d2e0",
  [ParticleType.Gunpowder]: "#3c3c3c",
  [ParticleType.Lava]:      "#c83205",
  [ParticleType.Acid]:      "#78f028",
  [ParticleType.Plant]:     "#1e8c28",
  [ParticleType.Ice]:       "#b4dcff",
  [ParticleType.Salt]:      "#e6e6e8",
  [ParticleType.Glass]:     "#b4d2e6",
  [ParticleType.Metal]:     "#8c919e",
  [ParticleType.Ember]:     "#c83c0a",
  [ParticleType.Mud]:       "#5a3c23",
  [ParticleType.Mercury]:   "#a0a5b6",
  [ParticleType.ToxicGas]:  "#8cb428",
  [ParticleType.Hydrogen]:  "#c8d4e8",
  [ParticleType.Fuse]:      "#783219",
  [ParticleType.Clone]:     "#b432c8",
  [ParticleType.Void]:      "#1e0a28",
};

export const PLACEABLE_TYPES: ParticleType[] = [
  ParticleType.Sand,
  ParticleType.Water,
  ParticleType.Stone,
  ParticleType.Fire,
  ParticleType.Wood,
  ParticleType.Oil,
  ParticleType.Smoke,
  ParticleType.Steam,
  ParticleType.Gunpowder,
  ParticleType.Lava,
  ParticleType.Acid,
  ParticleType.Plant,
  ParticleType.Ice,
  ParticleType.Salt,
  ParticleType.Glass,
  ParticleType.Metal,
  ParticleType.Ember,
  ParticleType.Mud,
  ParticleType.Mercury,
  ParticleType.ToxicGas,
  ParticleType.Hydrogen,
  ParticleType.Fuse,
  ParticleType.Clone,
  ParticleType.Void,
];
